name: Update RSS Feed

on:
  schedule:
    - cron: "40 * * * *"  # every hour
  workflow_dispatch:       # allow manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run fetch script
        run: python fetch.py
        
      - name: Commit and push updated feeds
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add feeds/*.xml index.html
          git commit -m "Update RSS feeds" || echo "No changes"
          git push


